---
- name: installing java
  hosts: all
  tasks:
    - name: apt update
      apt:
        update_cache: true

    - name: installing java
      apt: 
        name: default-jdk
        state: latest      
