---
- name: installing apachetomcat
  hosts: all
  tasks:
    - name: downloadong tomcat server packages
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
        dest: /opt

    - name: extracting tomcat packages
      unarchive:
        src: /opt/apache-tomcat-10.0.27.tar.gz
        dest: /opt
        remote_src: yes

    - name: stopping tomcat services      
      shell: nohup /opt/apache-tomcat-10.0.27/bin/shutdown.sh

    - name: start tomcat services
      shell: nohup /opt/apache-tomcat-10.0.27/bin/startup.sh    
